"""Add Global Products table

Revision ID: eda22f779a34
Revises: 69938122a947
Create Date: 2025-12-13 02:18:40.158596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda22f779a34'
down_revision: Union[str, Sequence[str], None] = '69938122a947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_products',
    sa.Column('global_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('base_description', sa.Text(), nullable=True),
    sa.Column('ean_code', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('global_id')
    )
    op.create_index(op.f('ix_global_products_category'), 'global_products', ['category'], unique=False)
    op.create_index(op.f('ix_global_products_ean_code'), 'global_products', ['ean_code'], unique=True)
    op.create_index(op.f('ix_global_products_global_id'), 'global_products', ['global_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_products_global_id'), table_name='global_products')
    op.drop_index(op.f('ix_global_products_ean_code'), table_name='global_products')
    op.drop_index(op.f('ix_global_products_category'), table_name='global_products')
    op.drop_table('global_products')
    # ### end Alembic commands ###
